version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - SERVER_DOMAIN=http://localhost:8000
      - BASE_DIR=/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-pw1234}
      - MARIADB_DATABASE=${DB_NAME:-database-name}
      - MARIADB_USER=${DB_USER:-default_user}
      - MARIADB_PASSWORD=${DB_PASSWORD:-pw1234}
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: